name: Run cypress tests
on:
       pull_request: 
              branches: [“main”]

jobs: 
       runs-tests: 
             runs-on: ubuntu-latest
             steps: 
           - name: Checkout
             uses: actions/checkout@v3
          # Install npm dependencies, cache them correctly
          # and run all Cypress tests
           - name: Cypress run
             uses: cypress-io/github-action@v5
             with: 
                   start: npm run start
                   build: npm run build
                   project: ./src
             env: 
                   MONGODB_URI: ${{ secrets.MONGODB_URI }}
